mod applet;
mod base64_module;
mod color_module;
mod http_module;
mod humanize_module;
mod json_module;
mod math_module;
mod random_module;
mod render_module;
mod schema_module;
mod starlark_bytes;
mod starlark_canvas;
mod starlark_color;
mod starlark_config;
mod starlark_duration;
mod starlark_file;
mod starlark_response;
pub mod starlark_time;
mod starlark_widgets;
mod time_module;

pub use applet::Applet;
